### ISSUE TITLE
Why there is no possibility to find this theme directly in the Linux Mint on Theme Settings?

### ISSUE THREAD

**Issue by karol92** [zagortenay333/new-minty#9]
I've found Your theme accidentally. My favourite theme hasn't look good after upgraded Mint from 18 to 18.1.
So I must say You have done a good job. Only a thin strip on the current application on the windows list instead a fully-colored button is that what I've wanted exactly.
So it will be great if this theme will be available directly in the OS.

**Comment by zagortenay333** [comment]
Thx :smile: , the reason is that I don't wan to maintain the zip packages; too much work. Would be nice if the cinna devs incorporated github into the spices site.

I'm in the process of updating all 6 of my themes, and I'll address that strip too (although I don't know whether you'll like it :smile: .)
